crofchantest: use sched_yield() instead of pthread_yield()
pthread_yield() is depracted and causes a warning with newer libcs,
causing crofchantest to fail to compile:

  CXX      crofchantest-crofchantest.o
crofchantest.cpp: In member function ‘virtual void crofchantest::handle_timeout(rofl::cthread&, uint32_t)’:
crofchantest.cpp:394:22: error: ‘int pthread_yield()’ is deprecated: pthread_yield is deprecated, use sched_yield instead [-Werror=deprecated-declarations]
  394 |         pthread_yield();
      |         ~~~~~~~~~~~~~^~
In file included from /usr/include/features.h:503,
                 from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/c++config.h:679,
                 from /usr/include/c++/13.2.1/cstdlib:41,
                 from /usr/include/c++/13.2.1/stdlib.h:36,
                 from crofchantest.cpp:8:
/usr/include/pthread.h:479:12: note: declared here
  479 | extern int __REDIRECT_NTH (pthread_yield, (void), sched_yield)
      |            ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>