crofsocktest: use sched_yield() instead of pthread_yield()
pthread_yield() is depracted and causes a warning with newer libcs,
causing crofsocktest to fail to compile:

crofsocktest.cpp: In member function ‘void crofsocktest::test()’:
crofsocktest.cpp:101:20: error: ‘int pthread_yield()’ is deprecated: pthread_yield is deprecated, use sched_yield instead [-Werror=deprecated-declarations]
  101 |       pthread_yield();
      |       ~~~~~~~~~~~~~^~
In file included from /usr/include/features.h:503,
                 from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/c++config.h:679,
                 from /usr/include/c++/13.2.1/cstdlib:41,
                 from /usr/include/c++/13.2.1/stdlib.h:36,
                 from crofsocktest.cpp:8:
/usr/include/pthread.h:479:12: note: declared here
  479 | extern int __REDIRECT_NTH (pthread_yield, (void), sched_yield)
      |

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>