cdaemon: include cstdint
cdaemon.cc is missing an include for <cstdint>, causing it to fail to
compile:

cdaemon.cc: In static member function ‘static void rofl::cdaemon::daemonize(const std::string&, const std::string&)’:
cdaemon.cc:75:7: error: ‘uint8_t’ was not declared in this scope
   75 |       uint8_t a;
      |       ^~~~~~~
cdaemon.cc:9:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    8 | #include "cdaemon.h"
  +++ |+#include <cstdint>
    9 | #include <stdexcept>
cdaemon.cc:77:28: error: ‘a’ was not declared in this scope
   77 |           read(pipefd[0], &a,
      |                            ^
cdaemon.cc:158:5: error: ‘uint8_t’ was not declared in this scope
  158 |     uint8_t a = 0;
      |     ^~~~~~~
cdaemon.cc:158:5: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
cdaemon.cc:159:27: error: ‘a’ was not declared in this scope
  159 |     if (write(pipefd[1], &a, sizeof(a)) < 0) {
      |                           ^
cdaemon.cc:164:5: error: ‘uint8_t’ was not declared in this scope
  164 |     uint8_t a = 1;
      |     ^~~~~~~
cdaemon.cc:164:5: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
cdaemon.cc:165:27: error: ‘a’ was not declared in this scope
  165 |     if (write(pipefd[1], &a, sizeof(a)) < 0) {
      |                           ^

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>